# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test

    - name: Jest Coverage Comment
      id: coverageComment
      uses: MishaKav/jest-coverage-comment@main
      with:
        coverage-summary-path: ./coverage/coverage-summary.json
        title: Jest Coverage
        summary-title: Summary
        badge-title: Coverage
        hide-comment: false
        create-new-comment: false
        hide-summary: false
        junitxml-title: Test unitaires
        junitxml-path: ./junit.xml
    - name: Check the output coverage
      run: |
        echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
        echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
        echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"
    - name: Create the badge
      if: github.ref == 'refs/heads/master'
      uses: schneegans/dynamic-badges-action@v1.6.0
      with:
        auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
        gistID: c61a425abff1acf2a6adee3c70c79346
        filename: jest-coverage-comment__main.json
        label: Coverage
        message: ${{ steps.coverageComment.outputs.coverage }}%
        color: ${{ steps.coverageComment.outputs.color }}
        namedLogo: typescript
